site_name: 额尼河的故事
site_url: https://sonriansonjo.github.io/mysite/
theme:
  name: material
  language: zh
  favicon: assets/images/logic.svg
  palette:
    scheme: default
    primary: teal
    accent: deep orange
  icon: 
    logo: material/notebook-edit
  features:
    - navigation.footer
    - navigation.instant
    - navigation.instant.progress
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.indexes
nav:
  - 首页: index.md          # 默认的首页
  - 预备知识: 
    - Prerequisites/index.md
    - 素朴集合论: Prerequisites/naive_set_theory.md   
    - 数学方法: Prerequisites/mathematical_method.md
    - 形式语言与元逻辑基础: Prerequisites/basic_formal_language_and_metalogic.md
  - 交替时态逻辑: 
    - ATL/index.md
    - 语法和语义: ATL/syntax_and_semantics.md
markdown_extensions:
  - def_list                      # 定义列表语法
  - toc:
      permalink: true             # 标题后生成永久链接符号
      toc_depth: 3                # 目录深度
  - pymdownx.caret                # ^^插入^^
  - pymdownx.mark                 # ==高亮==
  - pymdownx.smartsymbols         # 智能符号（-> 变成 →）
  - pymdownx.tasklist:                
      custom_checkbox: true       #任务列表
  - pymdownx.arithmatex:
      generic: true
  - markdown_checklist.extension
  - footnotes
extra_javascript:
  - javascripts/mathjax.js 
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js